services:
  - type: web
    name: route-analyzer
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_ENV
        value: production
    autoDeploy: true
